### ISSUE TITLE
Milestone 2 feedback: 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-solo_119#1]
Must fix: 

- [x]  images in your analysis read me do not work, therefore, I can not see your analysis. Besides, your analysis should be in a ipynb file with code we can run for each graph. Please change this to a ipynb file with code. 
- [x] use relative addressing instead of absolute addressing (example, do not use "r"C:\Users\Amrit\Desktop\School\data301\course-project-solo_119\data\data.raw\default of credit card clients.csv") 
- [x] add units to your graph axis

**Comment by AmrDhaliwal** [comment]
MAde all the appropriate changes to the Milestone project.
